### ISSUE TITLE
Using github.com/oam-dev/kubevela-core-api as dependency doesn't work

### ISSUE THREAD

**Issue by mredvard** [kubevela/kubevela-core-api#7]
When trying to download the module
`go get github.com/oam-dev/kubevela-core-api`
I get 
```
go: github.com/oam-dev/kubevela-core-api@v1.4.9 requires
        github.com/oam-dev/cluster-gateway@v1.4.0 requires
        sigs.k8s.io/apiserver-network-proxy@v0.0.30 requires
        sigs.k8s.io/apiserver-network-proxy/konnectivity-client@v0.0.0: reading sigs.k8s.io/apiserver-network-proxy/konnectivity-client/konnectivity-client/go.mod at revision konnectivity-client/v0.0.0: unknown revision konnectivity-client/v0.0.0
```

My go version 
`go version go1.18.4 linux/amd64`
It also happened to me on a mac.

**Comment by viggo-whh** [comment]
> When trying to download the module `go get github.com/oam-dev/kubevela-core-api` I get
> 
> ```
> go: github.com/oam-dev/kubevela-core-api@v1.4.9 requires
>         github.com/oam-dev/cluster-gateway@v1.4.0 requires
>         sigs.k8s.io/apiserver-network-proxy@v0.0.30 requires
>         sigs.k8s.io/apiserver-network-proxy/konnectivity-client@v0.0.0: reading sigs.k8s.io/apiserver-network-proxy/konnectivity-client/konnectivity-client/go.mod at revision konnectivity-client/v0.0.0: unknown revision konnectivity-client/v0.0.0
> ```
> 
> My go version `go version go1.18.4 linux/amd64` It also happened to me on a mac.

add "replace sigs.k8s.io/apiserver-network-proxy/konnectivity-client => sigs.k8s.io/apiserver-network-proxy/konnectivity-client v0.0.24" can fix.
